name: main CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BOOST_ROOT: ${{github.workspace}}/3rdparty/boost

jobs:
  windows-boost:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    env:
      BOOST_URL: https://sourceforge.net/projects/boost/files/boost/1.78.0/boost_1_78_0.tar.bz2/download
    steps:
    - name: Restore Boost cache
      uses: actions/cache@v3
      id: cache-boost
      with:
        path: ${{env.BOOST_ROOT}}
        key: boost
    - name: Install Boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
        BOOST_ROOT=$(echo $BOOST_ROOT | sed 's/\\/\//g')
        mkdir -p $BOOST_ROOT
        curl --progress-bar --location --output $BOOST_ROOT/download.tar.bz2 $BOOST_URL
        7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar.bz2 -y -bd
        7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar -y -bd
        cd $BOOST_ROOT && cp -r boost_*/* .
        rm -rf boost_*/* download.tar.bz2 download.tar
      shell: bash
  windows-debug-test:
    runs-on: windows-latest
    needs: windows-boost
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: |
        BOOST_ROOT=$(echo $BOOST_ROOT | sed 's/\\/\//g')
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DTHE_MODERN_C++_CHALLENGE_BUILD_TESTS=ON -DBOOST_ROOT=$BOOST_ROOT
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Debug
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Debug --output-on-failure
  windows-release-benchmark:
    runs-on: windows-latest
    needs: windows-boost
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: |
        BOOST_ROOT=$(echo $BOOST_ROOT | sed 's/\\/\//g')
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DTHE_MODERN_C++_CHALLENGE_BUILD_BENCHMARKS=ON -DBOOST_ROOT=$BOOST_ROOT
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
    - name: Benchmark
      working-directory: ${{github.workspace}}/build/benchmark/Release
      run: .\the_modern_c++_challenge_benchmark.exe
