name: publish docker

on:
  push:
    tags:
      - 'unixlike-builds-v*'

env:
  BOOST_ROOT: ${{ github.workspace }}/3rdparty/boost
  BOOST_URL: https://sourceforge.net/projects/boost/files/boost/1.78.0/boost_1_78_0.tar.bz2/download

jobs:
  publish-docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Wait for unixlike-gcc-release-docker job in unixlike-builds_ci workflow to succeed
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          check-name: unixlike-gcc-release-docker
          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download unixlike-gcc-release-docker artifact
        id: download-unixlike-gcc-release-docker-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          branch: unixlike-builds
          name: unixlike-gcc-release-docker-artifact
          path: /artifact
          run_id: ${{ env.GITHUB_SHA }}
          workflow_conclusion: success

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: /artifact

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            rturrado/tmcppc-binaries
          tags: |
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
