name: publish docker

on:
  push:
    tags:
      - 'unixlike-builds-v*'

jobs:
  publish-docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Wait for 'unixlike-builds CI' workflow to succeed
        uses: ArcticLampyrid/action-wait-for-workflow@v1.0.3
        with:
          sha: ${{ github.sha }}
          workflow: unixlike-builds_ci.yml

      - name: Download unixlike-gcc-release-docker artifact
        id: download-unixlike-gcc-release-docker-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          branch: unixlike-builds
          name: unixlike-gcc-release-docker-artifact
          path: artifact
          workflow: unixlike-builds_ci.yml
          workflow_conclusion: success

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifact

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            rturrado/tmcppc-binaries
          tags: |
            type=ref,event=tag

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: artifact/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
