# From: https://github.com/lukka/CppCMakeVcpkgTemplate/blob/main/.github/workflows/hosted-ninja-vcpkg_submod.yml
#
# The peculiarity of this workflow is that assumes vcpkg stored as a submodule of this repository.
# This workflow does the following:
# - Restores vcpkg artifacts from cache.
# - Sets up vcpkg if needed, then run CMake with CMakePreset.json using a configuration that leverages the vcpkg's toolchain file.
#   This will automatically run vcpkg to install dependencies described by the vcpkg.json manifest file.
#   It will be a no-op if those are restored from cache.
# - Finally builds the sources with Ninja.

name: unixlike-builds CI

on:
  push:
    branches:
      - 'unixlike-builds'

env:
  BOOST_ROOT: ${{ github.workspace }}/3rdparty/boost
  BOOST_URL: https://sourceforge.net/projects/boost/files/boost/1.78.0/boost_1_78_0.tar.bz2/download

jobs:
  unixlike-gcc-debug-github:
    runs-on: ubuntu-22.04
    steps:
      - name: Install gcc-12 and g++-12, and linux-headers
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install gcc-12 g++-12 linux-headers-$(uname -r)
          sudo update-alternatives \
              --install /usr/bin/gcc gcc /usr/bin/gcc-12 100 \
              --slave /usr/bin/g++ g++ /usr/bin/g++-12 \
              --slave /usr/bin/gcov gcov /usr/bin/gcov-12
        shell: bash

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Restore Boost cache
        uses: actions/cache@v3
        id: cache-boost
        with:
          path: ${{ env.BOOST_ROOT }}
          key: boost

      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
          BOOST_ROOT=$(echo $BOOST_ROOT | sed 's/\\/\//g')
          mkdir -p $BOOST_ROOT
          curl --progress-bar --location --output $BOOST_ROOT/download.tar.bz2 $BOOST_URL
          7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar.bz2 -y -bd
          7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar -y -bd
          cd $BOOST_ROOT && cp -r boost_*/* .
          rm -rf boost_*/* download.tar.bz2 download.tar
        shell: bash

      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      # Speed up builds by using ccache
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: unixlike-gcc-debug-github
          restore-keys: unixlike-gcc-debug-github
          verbose: 2

      # Run CMake to generate Ninja project files,
      # using the vcpkg's toolchain file to resolve and install the dependencies as specified in vcpkg.json
      - name: Configure and build tests in debug mode
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'unixlike-gcc-debug-github'
          buildPreset: 'unixlike-gcc-debug-github'

      - name: Run tests
        working-directory: ${{ github.workspace }}/out/build/unixlike-gcc-debug-github
        run: ctest -C Debug --output-on-failure
        shell: bash

      - name: Collect code coverage
        working-directory: ${{ github.workspace }}/out/build/unixlike-gcc-debug-github
        run: bash <(curl -s https://codecov.io/bash)
        shell: bash

  unixlike-gcc-release-docker:
    runs-on: ubuntu-22.04
    steps:
      - name: Install gcc-12 and g++-12, and linux-headers
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install gcc-12 g++-12 linux-headers-$(uname -r)
          sudo update-alternatives \
              --install /usr/bin/gcc gcc /usr/bin/gcc-12 100 \
              --slave /usr/bin/g++ g++ /usr/bin/g++-12 \
              --slave /usr/bin/gcov gcov /usr/bin/gcov-12
        shell: bash

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Restore Boost cache
        uses: actions/cache@v3
        id: cache-boost
        with:
          path: ${{ env.BOOST_ROOT }}
          key: boost

      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
          BOOST_ROOT=$(echo $BOOST_ROOT | sed 's/\\/\//g')
          mkdir -p $BOOST_ROOT
          curl --progress-bar --location --output $BOOST_ROOT/download.tar.bz2 $BOOST_URL
          7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar.bz2 -y -bd
          7z -o$BOOST_ROOT x $BOOST_ROOT/download.tar -y -bd
          cd $BOOST_ROOT && cp -r boost_*/* .
          rm -rf boost_*/* download.tar.bz2 download.tar
        shell: bash

      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or setup vcpkg for building artifacts
        uses: lukka/run-vcpkg@v10
        id: runvcpkg
        with:
          vcpkgJsonGlob: 'vcpkg.json'

      # Speed up builds by using ccache
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: unixlike-gcc-release-docker
          restore-keys: unixlike-gcc-release-docker
          verbose: 2

      # Run CMake to generate Ninja project files,
      # using the vcpkg's toolchain file to resolve and install the dependencies as specified in vcpkg.json
      - name: Configure and build tests and benchmarks in release mode
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'unixlike-gcc-release-docker'
          buildPreset: 'unixlike-gcc-release-docker'

      # Run benchmakrs (only if we are not pushing a tag)
      - name: Run benchmarks
        working-directory: ${{ github.workspace }}
        run: ./out/build/unixlike-gcc-release-docker/benchmark/Release/the_modern_c++_challenge_benchmark
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: unixlike-gcc-release-docker-artifact
          path: |
            ${{ github.workspace }}/Dockerfile
            ${{ github.workspace }}/out/build/unixlike-gcc-release-docker/_deps/freeimage-build/Release/libFreeImage.so
            ${{ github.workspace }}/out/build/unixlike-gcc-release-docker/benchmark/Release/the_modern_c++_challenge_benchmark
            ${{ github.workspace }}/out/build/unixlike-gcc-release-docker/src/Release/the_modern_c++_challenge
            ${{ github.workspace }}/out/build/unixlike-gcc-release-docker/test/Release/the_modern_c++_challenge_test
            ${{ github.workspace }}/res
